### ISSUE TITLE
Are cwr results published somewhere?

### ISSUE THREAD

**Issue by merlijn-sebrechts** [juju-solutions/bundle-cwr-ci#18]
cwr generates an html page with the results in. Is this published somewhere?

**Comment by ktsakalozos** [comment]
You should be able to get the cwr list of reports if you point your browser to http://<your_jenkins>:5000 . Remember to juju expose cwr first.

**Comment by merlijn-sebrechts** [comment]
Cool, thanks! Might be best to put this in the readme.

**Comment by pengale** [comment]
@galgalesh You can also get at the CWR results by looking at the Jenkins artifacts. At some point, I'd like to display them nicely in Jenkins, so that people don't have to worry about two ports.

In any case, +1 to putting it in the README. :-)

**Comment by merlijn-sebrechts** [comment]
@petevg What is a Jenkins Artifact?

**Comment by pengale** [comment]
@galgalesh if you click around in the Jenkins interface, you'll see a link to test "artifacts". For a failed test, you'll get a tarball containing the output of juju-crashump, along with the matrix logs and such.

For both failed and successful tests, you'll see some .xml files that represent the cwr output. .xml files aren't fun to read, though, so I recommend just viewing the cwr output on port 5000 for now. Eventually, I want to have Jenkins render those files in its own interface.

**Comment by kwmonroe** [comment]
There's a section on "Job status and logs" that just came in about a week ago:

https://github.com/juju-solutions/bundle-cwr-ci/blob/master/README.md#job-status-and-logs

@galgalesh, if that seems suitable, please close this out.  I'm also open to suggestions if this section needs to be expanded or moved elsewhere for better user visibility.  Thanks for the feedback!

**Comment by merlijn-sebrechts** [comment]
Looks good!
